language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-node -f Dockerfile.dev .

script:
  - docker run -e CI=true sgandla/docker-react npm run test