language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sgandla/docker-node -f Dockerfile.dev .

script:
  - docker run -e CI=true sgandla/docker-node npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-node"
  env: "DockerNode-env"
  bucket_name: "elasticbeanstalk-us-east-1-136627453761"
  bucket_path: "docker-node"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
